[package]
name = "picodata"
version = "24.6.1"
edition = "2021"
autotests = false
rust-version = "1.76.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.7"
blake3 = "=1.3.3"
bytes = "1.1"
chrono = "0.4.31"
clap = { version = "3", features = ["derive", "env"] }
comfy-table = "7.0.1"
either = "1.13.0"
file_shred = "1.1.3"
futures = "0.3.25"
indoc = "2"
lazy_static = "1.4"
libc = "0.2.108"
md5 = "0.7.0"
nix = { version = "0.26.4", features = ["fs", "term", "process", "signal"] }
once_cell = "1.17.1"
openssl = "0.10.64"
opentelemetry = "0.17"
pgwire = { version = "0.24.1", default-features = false, features = [
    "server-api",
] }
postgres-types = { version = "0.2.6", features = [
    "with-uuid-0_8",
    "array-impls",
    "with-serde_json-1",
    "with-time-0_3",
] }
raft = "0.7.0"
rand = "0.8.5"
rmp = "*"
rmp-serde = "1.0"
rmpv = { version = "1.0.0", features = ["with-serde"] }
rust_decimal = { version = "1.35.0", features = ["db-postgres"] }
rustyline = "12.0.0"
rustyline-derive = "0.10.0"
serde = "1.0"
serde_bytes = "0.11"
serde_json = "1.0"
serde_repr = "0.1"
serde_yaml = "0.9.25"
smallvec = "=1.13.2"
smol_str = "0.2.1"
socket2 = "0.5.7"
sqlparser = { version = "0.40.0", features = ["visitor"] }
tempfile = "3.8"
thiserror = "1.0"
time = { version = "0.3", features = ["parsing", "formatting", "macros"] }
uuid = { version = "0.8", features = ["v4"] } # TODO: update to 1.0
va_list = ">=0.1.4"

# Link- and ABI- related stuff
abi_stable = "0.11.2"
libloading = "0.8"
linkme = "0.3.14"

# Bundled modules e.g. picodata SDK
pico_proc_macro = { path = "./pico_proc_macro" }
picodata-plugin = { path = "./picodata-plugin", features = ["internal_test"] }

[dependencies.protobuf]
version = "2.27"
features = ["bytes", "with-bytes"]

[dependencies.sbroad-core]
version = "0.1"
path = "sbroad/sbroad-core"
features = ["tracing"]

[dependencies.slog]
version = "2.7.0"
features = ["max_level_trace", "release_max_level_trace"]

[dependencies.tarantool]
path = "./tarantool/tarantool"
version = "5.0"
features = ["picodata", "test"]

[dev-dependencies]
pretty_assertions = "0.6.1"

[build-dependencies]
git-version = "0.3.9"
jobserver = "0.1.26"
nix = { version = "0.26.4", features = ["fs"] }
quote = "^1.0"
syn = { version = "^1.0", features = ["full", "extra-traits", "printing"] }

[patch.crates-io]
nix = { git = "https://git.picodata.io/picodata/picodata/nix.git", branch = "fix-memfd-create-for-older-libc-backport-26-4" }

[patch."https://git.picodata.io/picodata/picodata/tarantool-module.git"]
tarantool = { path = "./tarantool/tarantool" }

[features]
dynamic_build = []
error_injection = []
load_test = []
webui = []

[lib]
doctest = true

[[test]]
name = "inner"
path = "test/inner.rs"
harness = false

[workspace]
members = [
    ".",
    "pico_proc_macro",
    "gostech/gostech-audit-log",
    "test/testplug",
    "test/plug_wrong_version",
]
